# -*- coding: utf-8 -*-
from . import ir_sequence
from . import product
from . import res_calendar_daymonth
from . import res_calendar_weekday
from . import stock_region
from . import stock_warehouse
from . import stock_warehouse_orderpoint
from . import procurement_group
from . import stock_picking
from . import stock_picking_type
from . import stock_move
from . import stock_move_line
from . import warehouse_transfer
from . import stock_rule
from . import stock_quant
from . import stock_inventory
from . import purchase_type_config
from . import purchase_order
from . import stock_location
from . import res_users
from . import stock_current_inventory