from . import res_partner
from . import sale_promo_header
from . import config_issue
from . import mobile_homepage_slide
from . import res_store
from . import request_update_card
from . import policy_terms
from . import configuration_login
from . import partner_wallet
from . import product_category_mobile
from . import product_template
from . import res_users
from . import stock_warehouse
from . import pos_sale_type
from . import show_case
from . import shipping_fee
from . import crm_voucher_lock
from . import pos_order
from . import pos_payment
from . import pos_payment_method
from . import config_qanda
from . import sale_promo_combo
from . import res_config_settings
from . import product_material
from . import coupon_app
from . import loyalty_reward
from . import loyalty_level
from . import crm_voucher_publish
from . import crm_voucher_info